// <auto-generated />
using System;
using Job_Portal_Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Job_Portal_Application.Migrations
{
    [DbContext(typeof(JobportalContext))]
    [Migration("20240628181930_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Job_Portal_Application.Models.AreasOfInterest", b =>
                {
                    b.Property<Guid>("AreasOfInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Lpa")
                        .HasColumnType("real");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AreasOfInterestId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("AreasOfInterests");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Credential", b =>
                {
                    b.Property<Guid>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("HasCode")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CredentialId");

                    b.ToTable("Credential");

                    b.HasData(
                        new
                        {
                            CredentialId = new Guid("bf0e4d0f-f8d4-4bb5-839e-2f34d9f6c6a4"),
                            HasCode = new byte[] { 201, 35, 127, 75, 69, 90, 101, 21, 157, 16, 247, 178, 98, 139, 58, 23, 51, 203, 67, 216, 65, 214, 171, 153, 22, 118, 228, 179, 83, 32, 47, 94, 180, 210, 52, 19, 41, 46, 201, 5, 55, 166, 105, 100, 184, 233, 147, 41, 31, 197, 183, 11, 80, 111, 11, 187, 214, 252, 26, 217, 126, 215, 45, 55, 190, 74, 194, 53, 145, 181, 219, 145, 62, 29, 38, 118, 223, 1, 102, 126, 77, 135, 234, 117, 69, 245, 34, 249, 85, 71, 206, 152, 149, 164, 161, 101, 103, 252, 213, 78, 83, 31, 29, 128, 238, 23, 5, 136, 88, 11, 156, 186, 99, 10, 203, 124, 152, 4, 251, 96, 88, 141, 233, 96, 156, 231, 113, 254 },
                            Password = new byte[] { 59, 255, 5, 2, 240, 113, 234, 194, 153, 188, 175, 151, 142, 241, 210, 148, 197, 98, 131, 235, 40, 1, 157, 202, 195, 90, 49, 64, 135, 42, 17, 7, 98, 240, 150, 162, 217, 159, 239, 241, 137, 11, 4, 8, 211, 202, 186, 82, 211, 61, 216, 243, 213, 31, 153, 5, 38, 99, 83, 82, 7, 130, 33, 32 },
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndYear")
                        .HasColumnType("date");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EducationId");

                    b.HasIndex("UserId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("EndYear")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartYear")
                        .HasColumnType("date");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExperienceId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DatePosted")
                        .HasColumnType("date");

                    b.Property<float?>("ExperienceRequired")
                        .HasColumnType("real");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Lpa")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TitleId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobActivity", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AppliedDate")
                        .HasColumnType("date");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ResumeViewed")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobActivities");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobSkills", b =>
                {
                    b.Property<Guid>("JobSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSkillsId");

                    b.HasIndex("JobId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("30c3a050-c257-4852-8744-d00dded1b622"),
                            SkillName = "HTML"
                        },
                        new
                        {
                            SkillId = new Guid("8b17679e-5c6e-418f-834b-f41cb4b8b00a"),
                            SkillName = "CSS"
                        },
                        new
                        {
                            SkillId = new Guid("e5dfcb9c-3f4e-4f31-a14e-3f97d6919e6c"),
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            SkillId = new Guid("067c60c1-a6cf-4b8a-b6d5-6a8d0441f1eb"),
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            SkillId = new Guid("fa624ad8-0caa-4e78-b6bd-e43e63af0ea5"),
                            SkillName = "React"
                        },
                        new
                        {
                            SkillId = new Guid("9aba24cd-c813-45af-8908-d30209788fbf"),
                            SkillName = "Angular"
                        },
                        new
                        {
                            SkillId = new Guid("9e4cc79c-a787-4ad4-9c7f-0390eae40abb"),
                            SkillName = "Vue"
                        },
                        new
                        {
                            SkillId = new Guid("b09d0bcc-3c2d-417c-bbd1-177a0d0fe1a1"),
                            SkillName = "Node.js"
                        },
                        new
                        {
                            SkillId = new Guid("07f9bf86-7661-4123-be87-dea35317b371"),
                            SkillName = "Express"
                        },
                        new
                        {
                            SkillId = new Guid("57330fa7-d64c-46f0-8129-0f3e9fc6c21c"),
                            SkillName = "Python"
                        },
                        new
                        {
                            SkillId = new Guid("3eeffde0-4bab-4878-8f93-ee26d11a2369"),
                            SkillName = "Django"
                        },
                        new
                        {
                            SkillId = new Guid("1516a9c6-4c7f-4eaa-b3b9-c8c99b32568d"),
                            SkillName = "Flask"
                        },
                        new
                        {
                            SkillId = new Guid("cabe5ebb-c7e3-4b0f-8d60-0b3c839437f4"),
                            SkillName = "Java"
                        },
                        new
                        {
                            SkillId = new Guid("a64968da-0d27-420e-9006-b097a93cb946"),
                            SkillName = "Spring"
                        },
                        new
                        {
                            SkillId = new Guid("18057da6-e0ca-4daa-b89d-68ea9d125185"),
                            SkillName = "Kotlin"
                        },
                        new
                        {
                            SkillId = new Guid("353c4eae-a7c1-45f7-b781-57b8256c9632"),
                            SkillName = "Swift"
                        },
                        new
                        {
                            SkillId = new Guid("0b92ba65-391a-4147-824e-d4ef442f57f4"),
                            SkillName = "Objective-C"
                        },
                        new
                        {
                            SkillId = new Guid("d377acf6-8078-4bc0-b9bd-0e615ef84a90"),
                            SkillName = "Ruby"
                        },
                        new
                        {
                            SkillId = new Guid("3ceef870-e43f-4789-ba5d-3a08362f9229"),
                            SkillName = "Rails"
                        },
                        new
                        {
                            SkillId = new Guid("9e42c6a7-5eb4-40e1-8e2e-5b687f984ea6"),
                            SkillName = "PHP"
                        },
                        new
                        {
                            SkillId = new Guid("adc3861b-f9e8-4594-aa64-8c45791b0c3d"),
                            SkillName = "C#"
                        },
                        new
                        {
                            SkillId = new Guid("bc484f38-033f-4771-944d-61735ae276e2"),
                            SkillName = "ASP.NET"
                        },
                        new
                        {
                            SkillId = new Guid("3651a089-9cb7-4233-820f-0651734cf87b"),
                            SkillName = "Azure"
                        },
                        new
                        {
                            SkillId = new Guid("c24cd5cc-e74b-42a7-86f4-1fcddcbdb924"),
                            SkillName = "AWS"
                        },
                        new
                        {
                            SkillId = new Guid("452696ad-ce35-425b-9ced-dfe21d7701ae"),
                            SkillName = "GCP"
                        },
                        new
                        {
                            SkillId = new Guid("27abfe34-c511-42c9-b6be-3afc9b8cae17"),
                            SkillName = "SQL"
                        },
                        new
                        {
                            SkillId = new Guid("7ad98392-a333-4385-8d7d-75433eb5cd8d"),
                            SkillName = "NoSQL"
                        },
                        new
                        {
                            SkillId = new Guid("ecb454c5-294c-47ff-9278-677c04652145"),
                            SkillName = "Docker"
                        },
                        new
                        {
                            SkillId = new Guid("b32b2d08-8fe2-43a1-b325-3499d79a0e43"),
                            SkillName = "Kubernetes"
                        },
                        new
                        {
                            SkillId = new Guid("ccc6a65c-2498-4806-b4d5-e785bbec7fba"),
                            SkillName = "GraphQL"
                        },
                        new
                        {
                            SkillId = new Guid("f106880e-78b9-41ca-a816-20f70ac63dc1"),
                            SkillName = "SASS"
                        },
                        new
                        {
                            SkillId = new Guid("e4069da1-3bc0-4394-8c36-6b471fb527c6"),
                            SkillName = "LESS"
                        },
                        new
                        {
                            SkillId = new Guid("5293920b-6599-41f2-810a-a2db395f6ac4"),
                            SkillName = "Webpack"
                        },
                        new
                        {
                            SkillId = new Guid("c2dc6a31-4691-454a-aec6-73b75b9104f2"),
                            SkillName = "Babel"
                        },
                        new
                        {
                            SkillId = new Guid("adf84009-3b96-4434-a91b-b3acf2895e6b"),
                            SkillName = "Redux"
                        },
                        new
                        {
                            SkillId = new Guid("ff893a54-fcf7-4cdf-a579-7e0506aadeb0"),
                            SkillName = "MobX"
                        },
                        new
                        {
                            SkillId = new Guid("77526fe6-86fb-4605-8add-ce0a53b9dbd6"),
                            SkillName = "Jest"
                        },
                        new
                        {
                            SkillId = new Guid("ccda3852-6d5d-49c8-84f9-c847fede24fb"),
                            SkillName = "Mocha"
                        },
                        new
                        {
                            SkillId = new Guid("e7ea90fd-6545-4f26-afdd-7baabc432c94"),
                            SkillName = "Chai"
                        },
                        new
                        {
                            SkillId = new Guid("d70e473e-3bb4-4a25-a154-e06e20fa6d04"),
                            SkillName = "Cucumber"
                        },
                        new
                        {
                            SkillId = new Guid("0c359f7d-8fde-420e-94fb-d6ba8c2b8900"),
                            SkillName = "C++"
                        },
                        new
                        {
                            SkillId = new Guid("0b4078c9-3883-4364-8ca7-2cf5c480396f"),
                            SkillName = "C"
                        },
                        new
                        {
                            SkillId = new Guid("e1292581-50bf-4479-8701-48bae7b4eaa4"),
                            SkillName = "Go"
                        },
                        new
                        {
                            SkillId = new Guid("6102c69b-262f-451f-82dc-f0be8bc394ee"),
                            SkillName = "Rust"
                        },
                        new
                        {
                            SkillId = new Guid("103eb993-6b3e-4064-bc8b-71ade88c3d4f"),
                            SkillName = "Perl"
                        },
                        new
                        {
                            SkillId = new Guid("c41ca4d8-6e3a-4584-9c24-b38a9bfcf412"),
                            SkillName = "Shell Scripting"
                        },
                        new
                        {
                            SkillId = new Guid("487e42ce-8919-455f-b9f5-6017778cdf6b"),
                            SkillName = "PowerShell"
                        },
                        new
                        {
                            SkillId = new Guid("b2021b7e-f1b8-4d91-88f4-1f6e50cab60b"),
                            SkillName = "Terraform"
                        },
                        new
                        {
                            SkillId = new Guid("1a18f503-4705-4d4b-94a8-d9a5b83a7019"),
                            SkillName = "Ansible"
                        },
                        new
                        {
                            SkillId = new Guid("97fc1054-55cc-4b8a-b0fd-e1de7a8aa54c"),
                            SkillName = "Puppet"
                        },
                        new
                        {
                            SkillId = new Guid("64f5a7e9-7fc8-4507-b24f-2c10e468f014"),
                            SkillName = "Chef"
                        },
                        new
                        {
                            SkillId = new Guid("f38f9581-5d99-490b-9672-d05853ba6585"),
                            SkillName = "Splunk"
                        },
                        new
                        {
                            SkillId = new Guid("06ed34cc-985b-418c-aea0-2263a430e41f"),
                            SkillName = "ELK Stack"
                        },
                        new
                        {
                            SkillId = new Guid("bb83e719-600f-4e26-ae8f-236c00ccfea1"),
                            SkillName = "Prometheus"
                        },
                        new
                        {
                            SkillId = new Guid("5809d6ae-55e0-4262-925a-e724c31f377b"),
                            SkillName = "Grafana"
                        },
                        new
                        {
                            SkillId = new Guid("a002cb5f-9c92-4cc1-b860-20871a608e00"),
                            SkillName = "Jenkins"
                        },
                        new
                        {
                            SkillId = new Guid("b232bde8-ffc3-4d0d-b230-9bca452b8690"),
                            SkillName = "CircleCI"
                        },
                        new
                        {
                            SkillId = new Guid("445401ca-70a1-4fe4-a96c-3a235f2ae3bb"),
                            SkillName = "Travis CI"
                        },
                        new
                        {
                            SkillId = new Guid("98b966b8-22da-4d22-81e3-369f25e6ba07"),
                            SkillName = "Git"
                        },
                        new
                        {
                            SkillId = new Guid("100a275a-2423-4774-b9e7-d266ad117369"),
                            SkillName = "Mercurial"
                        },
                        new
                        {
                            SkillId = new Guid("e229520a-9447-4dc2-883e-395efc5785db"),
                            SkillName = "Subversion"
                        },
                        new
                        {
                            SkillId = new Guid("27f289e6-8667-4c9a-b053-18c73e509ff2"),
                            SkillName = "Project Management"
                        },
                        new
                        {
                            SkillId = new Guid("741faa07-7e34-4008-b762-fb32e070cd72"),
                            SkillName = "Agile Methodology"
                        },
                        new
                        {
                            SkillId = new Guid("3eb128ae-b84d-4750-95d2-d3771b3e39f5"),
                            SkillName = "Scrum"
                        },
                        new
                        {
                            SkillId = new Guid("69f00980-a4ca-4ce1-b281-683aa4a1b55d"),
                            SkillName = "Kanban"
                        },
                        new
                        {
                            SkillId = new Guid("cc1ffa5f-586b-4778-a649-a3b5519fc074"),
                            SkillName = "Communication"
                        },
                        new
                        {
                            SkillId = new Guid("446f44ea-c3a9-475d-b061-1b65ed037eff"),
                            SkillName = "Teamwork"
                        },
                        new
                        {
                            SkillId = new Guid("8e52eaa0-2342-4adb-b4f1-947417e5ea23"),
                            SkillName = "Leadership"
                        },
                        new
                        {
                            SkillId = new Guid("73663c18-e372-47c6-977a-e9ca52ca9969"),
                            SkillName = "Problem-Solving"
                        },
                        new
                        {
                            SkillId = new Guid("d10a8f6c-bafd-4b46-9de2-547598957377"),
                            SkillName = "Time Management"
                        },
                        new
                        {
                            SkillId = new Guid("d22d42a8-ae0f-4ea4-99ac-2e342360dff7"),
                            SkillName = "Critical Thinking"
                        },
                        new
                        {
                            SkillId = new Guid("d52285f0-960e-4dba-8819-ea856bcc2e2d"),
                            SkillName = "Creativity"
                        },
                        new
                        {
                            SkillId = new Guid("2b83b500-be59-4846-a536-83df8502891c"),
                            SkillName = "Adaptability"
                        },
                        new
                        {
                            SkillId = new Guid("355b3651-66a8-4683-95cc-b5fd5af64264"),
                            SkillName = "Attention to Detail"
                        },
                        new
                        {
                            SkillId = new Guid("93660f09-81a0-4e5c-9d7b-be2454a7f8e8"),
                            SkillName = "Conflict Resolution"
                        },
                        new
                        {
                            SkillId = new Guid("6bc950d3-7bef-4390-9ac4-a800824e8c7f"),
                            SkillName = "Negotiation"
                        },
                        new
                        {
                            SkillId = new Guid("260563cd-ffe6-4490-b87e-34dd57611146"),
                            SkillName = "Customer Service"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Title", b =>
                {
                    b.Property<Guid>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TitleId");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            TitleId = new Guid("0a6274f6-2f81-4c81-9697-9532e9a1d13a"),
                            TitleName = "Full Stack Developer"
                        },
                        new
                        {
                            TitleId = new Guid("a6a2a59b-942b-4757-aaa0-04b5382726ea"),
                            TitleName = "Front End Developer"
                        },
                        new
                        {
                            TitleId = new Guid("38c10386-f241-47a4-9562-fc6fe553511d"),
                            TitleName = "Back End Developer"
                        },
                        new
                        {
                            TitleId = new Guid("faf14050-1b4a-4164-ae27-17c143e51b26"),
                            TitleName = "Software Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("fd888b70-bfdd-442a-8cd0-647ce7da45fb"),
                            TitleName = "Data Scientist"
                        },
                        new
                        {
                            TitleId = new Guid("b94f2568-ee49-4380-a107-f8e16c435470"),
                            TitleName = "DevOps Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("92fe2398-0765-4a70-9b73-a339f5d43432"),
                            TitleName = "Product Manager"
                        },
                        new
                        {
                            TitleId = new Guid("7f6b1602-f380-4e83-b63f-7397351f3ed2"),
                            TitleName = "Project Manager"
                        },
                        new
                        {
                            TitleId = new Guid("29ad869c-a1fb-4abb-84cd-789b8aeab07d"),
                            TitleName = "Business Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("4c5d6a4c-deb6-49e0-ab40-8bb73f54d12d"),
                            TitleName = "QA Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("96c45bc0-641c-42a6-bfa9-28dcbfd2ad5c"),
                            TitleName = "UI/UX Designer"
                        },
                        new
                        {
                            TitleId = new Guid("5ca425be-e1f4-4574-9828-ce33eb9d5289"),
                            TitleName = "Mobile Developer"
                        },
                        new
                        {
                            TitleId = new Guid("aa51ba32-6fea-448c-8659-b9c8778141de"),
                            TitleName = "Security Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("db75f17c-a37f-4f50-b30e-f0969e39ecd1"),
                            TitleName = "Network Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("b42e8bd7-a63f-4969-8acc-854013fbc8ba"),
                            TitleName = "Systems Administrator"
                        },
                        new
                        {
                            TitleId = new Guid("cc63f8a3-de37-4d3f-8805-29f78075dbe2"),
                            TitleName = "Database Administrator"
                        },
                        new
                        {
                            TitleId = new Guid("af16fc7a-2713-49ee-8684-d2d4a2e6c557"),
                            TitleName = "Cloud Architect"
                        },
                        new
                        {
                            TitleId = new Guid("91062b7f-61e6-443b-bf1a-83f1aaade9cd"),
                            TitleName = "Machine Learning Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("6e3cce29-39ca-4a44-8776-9fd9643ee30c"),
                            TitleName = "Artificial Intelligence Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("1bc4f455-22aa-4c7f-8d5f-9b6a5cac35b5"),
                            TitleName = "Technical Support Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("63caaed3-fa26-4642-9a1d-6623520f4f2b"),
                            TitleName = "Cloud Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("0af28709-faf9-4037-95ae-d86bfc5376ad"),
                            TitleName = "Database Developer"
                        },
                        new
                        {
                            TitleId = new Guid("409fcddf-a835-480b-811c-df6b02e72682"),
                            TitleName = "Blockchain Developer"
                        },
                        new
                        {
                            TitleId = new Guid("20d7c477-fa53-45cb-9547-10357fbcc9b4"),
                            TitleName = "Game Developer"
                        },
                        new
                        {
                            TitleId = new Guid("e05c90bf-20e5-4d7d-92e6-79ed6b977aca"),
                            TitleName = "VR/AR Developer"
                        },
                        new
                        {
                            TitleId = new Guid("4831e2fc-f6d6-4ff2-aad1-8e9801d49e36"),
                            TitleName = "Site Reliability Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("b423e33a-9fcb-4ed4-abb2-dc86fd874488"),
                            TitleName = "Embedded Systems Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("b60db7c5-2506-4dd7-bc77-551bedd2d9e5"),
                            TitleName = "Firmware Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("23f6baee-38cd-4890-9ac5-4ca5535ff442"),
                            TitleName = "IoT Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("b704db78-979b-4870-87b0-06401e32a760"),
                            TitleName = "Robotics Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("5b1d949b-3f24-465a-b01d-ee5e33bb0f2a"),
                            TitleName = "Computer Vision Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("934b2daa-61f7-41c7-889a-587370af4a48"),
                            TitleName = "Natural Language Processing Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("ec8d27b2-9a8b-45f3-9851-f3a2b4825be9"),
                            TitleName = "Bioinformatics Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("0cf98239-b587-42ce-bc38-9fb89075c90b"),
                            TitleName = "Cryptographer"
                        },
                        new
                        {
                            TitleId = new Guid("d41f99f7-06d7-4859-9b39-d4cc550e343a"),
                            TitleName = "Penetration Tester"
                        },
                        new
                        {
                            TitleId = new Guid("f5feb18b-09c6-4003-8a03-7bcb413d51a2"),
                            TitleName = "Incident Response Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("c1844c00-78ff-4119-9861-4df0145563ac"),
                            TitleName = "Cloud Security Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("b3677100-83eb-4f5e-857b-fa51b1d18e0a"),
                            TitleName = "Ethical Hacker"
                        },
                        new
                        {
                            TitleId = new Guid("98670a8c-ae31-4b53-a528-ecd95bd21d44"),
                            TitleName = "Digital Forensics Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("02574ea6-c8f2-4b2e-a411-4edde55a2b4a"),
                            TitleName = "IT Support Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("d2d98351-09d8-418b-a146-7cefc1a4ec07"),
                            TitleName = "Help Desk Technician"
                        },
                        new
                        {
                            TitleId = new Guid("08e39665-8f26-4939-a186-6c4266edc305"),
                            TitleName = "Technical Writer"
                        },
                        new
                        {
                            TitleId = new Guid("6103537f-5f3a-48cb-aa2c-61508dcb5616"),
                            TitleName = "UX Researcher"
                        },
                        new
                        {
                            TitleId = new Guid("de936739-f694-4e10-bc78-73a93f42734b"),
                            TitleName = "IT Manager"
                        },
                        new
                        {
                            TitleId = new Guid("98f6d1dd-a4e5-4116-b400-c0874f7f2d80"),
                            TitleName = "IT Director"
                        },
                        new
                        {
                            TitleId = new Guid("f245c806-dbc4-4d55-b82a-0c180b05d726"),
                            TitleName = "Chief Technology Officer"
                        },
                        new
                        {
                            TitleId = new Guid("df1e5823-a137-4d97-9687-7eb529a670f2"),
                            TitleName = "Scrum Master"
                        },
                        new
                        {
                            TitleId = new Guid("e3202513-acb4-4b05-bbc2-d67bd63cbb25"),
                            TitleName = "Agile Coach"
                        },
                        new
                        {
                            TitleId = new Guid("264a929b-896e-4166-a53a-6243f5e7955d"),
                            TitleName = "Technical Lead"
                        },
                        new
                        {
                            TitleId = new Guid("3f93f4c1-2fe4-4b27-a499-2479fbae9f35"),
                            TitleName = "Software Architect"
                        },
                        new
                        {
                            TitleId = new Guid("06f2acf9-ec58-4d83-9c39-ecb8ee8d8afb"),
                            TitleName = "Engineering Manager"
                        },
                        new
                        {
                            TitleId = new Guid("2fc9daae-6003-461a-907d-295a77157881"),
                            TitleName = "Chief Information Officer"
                        },
                        new
                        {
                            TitleId = new Guid("51981627-545f-4b95-8114-65ee7d160938"),
                            TitleName = "Chief Data Officer"
                        },
                        new
                        {
                            TitleId = new Guid("7b8a100d-d915-4ba8-ac20-4307065961dc"),
                            TitleName = "IT Consultant"
                        },
                        new
                        {
                            TitleId = new Guid("e2959333-a5d5-48b1-a314-d592b138c3fe"),
                            TitleName = "Enterprise Architect"
                        },
                        new
                        {
                            TitleId = new Guid("7c60ce39-d3f9-4383-9383-6d0aa3af5581"),
                            TitleName = "Security Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("36de31e6-8352-4361-a38a-2a863b387908"),
                            TitleName = "Data Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("86cc2889-f578-4f94-b7ec-0d73b6632080"),
                            TitleName = "Data Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("fde9f697-f47b-40ed-bb34-f3882d15ae99"),
                            TitleName = "Business Intelligence Developer"
                        },
                        new
                        {
                            TitleId = new Guid("c8d7a1cc-6a31-4333-8a56-13a05a6da260"),
                            TitleName = "Big Data Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("2ac07f01-eac4-4116-9193-6fd8baa4495e"),
                            TitleName = "Hadoop Developer"
                        },
                        new
                        {
                            TitleId = new Guid("3569ac60-11a7-4d83-a3f2-e87121aeb328"),
                            TitleName = "Solution Architect"
                        },
                        new
                        {
                            TitleId = new Guid("8df47acd-fe16-4c10-9f8c-e43a52cb0a43"),
                            TitleName = "DevSecOps Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("a35b3c8e-7593-4c43-9f25-04041e9d8e58"),
                            TitleName = "Information Security Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("caf2a8a5-bbe7-4ddc-8efe-5cc4b0e19f95"),
                            TitleName = "Site Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("521941d9-e89c-40c6-b225-deed7100e8e2"),
                            TitleName = "Hardware Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("a66ad865-a29d-41bf-a730-b879dd1cff54"),
                            TitleName = "IT Auditor"
                        },
                        new
                        {
                            TitleId = new Guid("da00b5c9-e2b0-4b7b-be72-2aa4e1774f95"),
                            TitleName = "Compliance Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("93b98550-caf7-4943-8a91-bd8c08f902d9"),
                            TitleName = "Quality Assurance Manager"
                        },
                        new
                        {
                            TitleId = new Guid("33adebe9-9abb-4240-99ba-5c60646f8726"),
                            TitleName = "IT Operations Manager"
                        },
                        new
                        {
                            TitleId = new Guid("44285da5-b767-41d3-904f-ca3f06e70ac0"),
                            TitleName = "Release Manager"
                        },
                        new
                        {
                            TitleId = new Guid("f73bb07c-9bf6-4a20-bf32-c5f9f3017671"),
                            TitleName = "Build Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("e3c7621b-7d20-4f1c-bbd6-e5d43fb4f387"),
                            TitleName = "Configuration Manager"
                        },
                        new
                        {
                            TitleId = new Guid("64b6303c-7a31-4ccb-94a0-1ca9fcb989e8"),
                            TitleName = "IT Trainer"
                        },
                        new
                        {
                            TitleId = new Guid("00c16778-7bd5-47f3-ad1f-c18d83eab6dc"),
                            TitleName = "ERP Consultant"
                        },
                        new
                        {
                            TitleId = new Guid("1586504d-f29f-4f37-80cc-98d8838b4713"),
                            TitleName = "CRM Developer"
                        },
                        new
                        {
                            TitleId = new Guid("a53ab615-3ca0-4993-ac09-81b7f8535034"),
                            TitleName = "Business Systems Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("f174a4b9-42f1-4b82-8e06-cf5e52fe7724"),
                            TitleName = "Systems Analyst"
                        },
                        new
                        {
                            TitleId = new Guid("b7400fc5-a39f-4a00-9eb3-507dda053840"),
                            TitleName = "Network Architect"
                        },
                        new
                        {
                            TitleId = new Guid("0ddbf4ef-859c-4e9a-a36c-c39201e8ad71"),
                            TitleName = "Telecommunications Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("6f583b9b-2e81-4185-8f10-788fed87ca6a"),
                            TitleName = "IT Procurement Manager"
                        },
                        new
                        {
                            TitleId = new Guid("79d2b753-50c2-4f07-82d7-6bc5756d6471"),
                            TitleName = "Enterprise Systems Manager"
                        },
                        new
                        {
                            TitleId = new Guid("f1c040f6-5b9e-4815-a858-61fc036d987c"),
                            TitleName = "Chief Information Security Officer"
                        },
                        new
                        {
                            TitleId = new Guid("8c2c5e23-9a5f-45fc-809a-a34bc4ec3828"),
                            TitleName = "Information Technology Specialist"
                        },
                        new
                        {
                            TitleId = new Guid("eb93ce79-2d85-477d-8aa8-0155b6f965fb"),
                            TitleName = "Application Support Engineer"
                        },
                        new
                        {
                            TitleId = new Guid("fd3c4d12-5816-4c25-906e-d09b518f1241"),
                            TitleName = "IT Project Coordinator"
                        },
                        new
                        {
                            TitleId = new Guid("56b517d2-00ae-4fcb-b4ef-61dbb5f639bd"),
                            TitleName = "IT Project Manager"
                        },
                        new
                        {
                            TitleId = new Guid("ca0dffcc-733a-4e60-95fb-04970b593949"),
                            TitleName = "IT Director"
                        },
                        new
                        {
                            TitleId = new Guid("18d06394-1d07-4968-8837-160eced1730c"),
                            TitleName = "Chief Information Officer"
                        },
                        new
                        {
                            TitleId = new Guid("1dbbecb9-5bf5-4b12-ac79-e829111d8d3c"),
                            TitleName = "Data Privacy Officer"
                        },
                        new
                        {
                            TitleId = new Guid("2d0a527e-de8d-4f64-b7f6-ba22af4474b0"),
                            TitleName = "Systems Integrator"
                        },
                        new
                        {
                            TitleId = new Guid("693ad10c-ccdd-4935-ac27-72981fbcce07"),
                            TitleName = "Software Development Manager"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AboutMe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioLink")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("df9b412d-c5e7-4bbf-8883-89c469f22ec2"),
                            CredentialId = new Guid("bf0e4d0f-f8d4-4bb5-839e-2f34d9f6c6a4"),
                            Dob = new DateOnly(1, 1, 1),
                            Email = "Admin@jobportal.com",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Job_Portal_Application.Models.UserSkills", b =>
                {
                    b.Property<Guid>("UserSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserSkillsId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.AreasOfInterest", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("AreasOfInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Credential", "Credential")
                        .WithOne()
                        .HasForeignKey("Job_Portal_Application.Models.Company", "CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Education", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Experience", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", null)
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.Title", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobActivity", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Job", "Job")
                        .WithMany("JobActivities")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", "User")
                        .WithMany("JobActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.JobSkills", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Credential", "Credential")
                        .WithOne()
                        .HasForeignKey("Job_Portal_Application.Models.User", "CredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.UserSkills", b =>
                {
                    b.HasOne("Job_Portal_Application.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Application.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.Job", b =>
                {
                    b.Navigation("JobActivities");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("Job_Portal_Application.Models.User", b =>
                {
                    b.Navigation("AreasOfInterests");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("JobActivities");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
